apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mycomponent-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mycomponent-2
    app.kubernetes.io/part-of: application-sample
  name: mycomponent-2
  namespace: karthik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mycomponent-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mycomponent-2
    spec:
      containers:
      - image: quay.io/karthik_jk/devfile-nodejs
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
